spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
server:
  port: 8060